apiVersion: anywhere.eks.amazonaws.com/v1alpha1
kind: Cluster
metadata:
  name: release-i-0cee9-aa583ea
  namespace: default
spec:
  bundlesRef:
    apiVersion: anywhere.eks.amazonaws.com/v1alpha1
    name: bundles-14
    namespace: eksa-system
  clusterNetwork:
    cniConfig:
      cilium: {}
    pods:
      cidrBlocks:
      - 192.168.0.0/16
    services:
      cidrBlocks:
      - 10.96.0.0/12
  controlPlaneConfiguration:
    count: 1
  datacenterRef:
    kind: DockerDatacenterConfig
    name: release-i-0cee9-aa583ea
  externalEtcdConfiguration:
    count: 1
  gitOpsRef:
    kind: FluxConfig
    name: eksa-test-emaj6
  kubernetesVersion: "1.23"
  managementCluster:
    name: release-i-0cee9-aa583ea
  workerNodeGroupConfigurations:
  - count: 3
    name: md-0

---
apiVersion: anywhere.eks.amazonaws.com/v1alpha1
kind: DockerDatacenterConfig
metadata:
  name: release-i-0cee9-aa583ea
  namespace: default
spec: {}

---
apiVersion: anywhere.eks.amazonaws.com/v1alpha1
kind: FluxConfig
metadata:
  name: eksa-test-emaj6
  namespace: default
spec:
  branch: aws-staging-eks-a-test-4c87e23d-15ee-4816-9a5e-31a735909f3f-24
  clusterConfigPath: aws-staging-eks-a-test-4c87e23d-15ee-4816-9a5e-31a735909f3f-24
  git:
    repositoryUrl: ssh://git@github.com/that-jetpack-guy/aws-staging-eks-a-test-4c87e23d-15ee-4816-9a5e-31a735909f3f-24.git
  systemNamespace: default

---
